#!/bin/bash
chmod +x ~/ngit/ngit

op=$1
shift

if [ -f ~/ngit/$op.sh ]; then
	~/ngit/$op.sh $@
elif [[ -z $op ]]; then
	printf "\nngit version 0.01\n$(git --version)\n\nNgit is a Git wrapper born out of laziness that attempts to make Git easier to use.\n"
else
	echo "ngit: command not found"
fi
